[package]
name = "graphql-directive-analyzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "graphql-directive-analyzer"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0"
gql-safeguard-lib = { path = "../lib" }