[package]
name = "gql-safeguard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gql-safeguard"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0"
gql-safeguard-lib = { path = "../lib" }