name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Update optional dependencies versions
        run: node scripts/bump-dependencies.mjs

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: Release new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: release
    if: needs.release.outputs.published == 'true'
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: gql-safeguard-linux-x64
            package: gql-safeguard/linux-x64
            os_name: linux
            cpu: x64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: gql-safeguard-linux-arm64
            package: gql-safeguard/linux-arm64
            os_name: linux
            cpu: arm64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: gql-safeguard-darwin-x64
            package: gql-safeguard/darwin-x64
            os_name: darwin
            cpu: x64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: gql-safeguard-darwin-arm64
            package: gql-safeguard/darwin-arm64
            os_name: darwin
            cpu: arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: gql-safeguard-win32-x64.exe
            package: gql-safeguard/win32-x64
            os_name: win32
            cpu: x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cross (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            cross build --release --target ${{ matrix.target }} -p gql-safeguard
          else
            cargo build --release --target ${{ matrix.target }} -p gql-safeguard
          fi
        shell: bash

      - name: Package Binary
        run: |
          mkdir -p npm-package
          if [[ "${{ matrix.os_name }}" == "win32" ]]; then
            cp target/${{ matrix.target }}/release/gql-safeguard.exe npm-package/
            EXE_SUFFIX=".exe"
          else
            cp target/${{ matrix.target }}/release/gql-safeguard npm-package/
            EXE_SUFFIX=""
          fi
          
          # Copy README, LICENSE, and CHANGELOG for binary package
          cp npm/README.md npm-package/
          cp LICENSE npm-package/
          cp CHANGELOG.md npm-package/ || echo "No changelog found"
          
          # Get version from package.json
          VERSION=$(node -p "require('./package.json').version")
          
          # Generate package.json from template
          PACKAGE_NAME="@${{ matrix.package }}"
          OS="${{ matrix.os_name }}"
          CPU="${{ matrix.cpu }}"
          if [[ "${{ matrix.os_name }}" == "win32" ]]; then
            EXE_SUFFIX=".exe"
          else
            EXE_SUFFIX=""
          fi
          
          export VERSION PACKAGE_NAME OS CPU EXE_SUFFIX
          envsubst < npm/package.json.tmpl > npm-package/package.json
          
          # Log final package.json for debugging
          echo "Final package.json content:"
          cat npm-package/package.json
        shell: bash
        env:
          PACKAGE_NAME: "@${{ matrix.package }}"
          OS: ${{ matrix.os_name }}
          CPU: ${{ matrix.cpu }}
          EXE_SUFFIX: ${{ matrix.os_name == 'win32' && '.exe' || '' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: npm-package/
          retention-days: 1

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - name: gql-safeguard-linux-x64
            package: gql-safeguard/linux-x64
          - name: gql-safeguard-linux-arm64
            package: gql-safeguard/linux-arm64
          - name: gql-safeguard-darwin-x64
            package: gql-safeguard/darwin-x64
          - name: gql-safeguard-darwin-arm64
            package: gql-safeguard/darwin-arm64
          - name: gql-safeguard-win32-x64.exe
            package: gql-safeguard/win32-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/

      - name: Publish platform package
        run: |
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-base:
    name: Publish base package
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish base package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}